apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: synergychat-api
  ports:
    - protocol: TCP # http access
      port: 80 # service port
      targetPort: 8080 # pod ports
#      nodePort: 30080
#  type: NodePort