apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  selector:
    app: synergychat-crawler
  ports:
    - protocol: TCP # http access
      port: 80 # service port
      targetPort: 8080 # pod ports
